/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_Gypsy_Server
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_Gypsy_Server

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freedesktop_Gypsy_Server_create (DBusGProxy *proxy, const char * IN_device, char** OUT_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "Create", error, G_TYPE_STRING, IN_device, G_TYPE_INVALID, DBUS_TYPE_G_OBJECT_PATH, OUT_path, G_TYPE_INVALID);
}

typedef void (*org_freedesktop_Gypsy_Server_create_reply) (DBusGProxy *proxy, char *OUT_path, GError *error, gpointer userdata);

static void
org_freedesktop_Gypsy_Server_create_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char* OUT_path;
  dbus_g_proxy_end_call (proxy, call, &error, DBUS_TYPE_G_OBJECT_PATH, &OUT_path, G_TYPE_INVALID);
  (*(org_freedesktop_Gypsy_Server_create_reply)data->cb) (proxy, OUT_path, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freedesktop_Gypsy_Server_create_async (DBusGProxy *proxy, const char * IN_device, org_freedesktop_Gypsy_Server_create_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Create", org_freedesktop_Gypsy_Server_create_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_device, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freedesktop_Gypsy_Server_shutdown (DBusGProxy *proxy, const char* IN_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "Shutdown", error, DBUS_TYPE_G_OBJECT_PATH, IN_path, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_freedesktop_Gypsy_Server_shutdown_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_freedesktop_Gypsy_Server_shutdown_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_freedesktop_Gypsy_Server_shutdown_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freedesktop_Gypsy_Server_shutdown_async (DBusGProxy *proxy, const char* IN_path, org_freedesktop_Gypsy_Server_shutdown_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Shutdown", org_freedesktop_Gypsy_Server_shutdown_async_callback, stuff, _dbus_glib_async_data_free, DBUS_TYPE_G_OBJECT_PATH, IN_path, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freedesktop_Gypsy_Server */

G_END_DECLS
